// Mocks generated by Mockito 5.4.0 from annotations
// in chat_gpt_app/test/repositories/openai_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:chat_gpt_app/chat/domain/models/message_model.dart' as _i4;
import 'package:chat_gpt_app/chat/domain/repositories/openai_repository.dart'
    as _i2;
import 'package:chat_gpt_sdk/chat_gpt_sdk.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [OpenAIRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenAIRepository extends _i1.Mock implements _i2.OpenAIRepository {
  MockOpenAIRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.MessageModel?> sendRequest(_i5.CompleteText? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendRequest,
          [request],
        ),
        returnValue: _i3.Future<_i4.MessageModel?>.value(),
      ) as _i3.Future<_i4.MessageModel?>);
}
